language: php
php:
  - 7.0

services:
  - mongodb

before_script:
  #- source ./data/mongo-php-driver-installer.sh
  - composer install

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text

notifications:
  email: false